export enum Screens {
  WELCOME_SCREEN = "WELCOME_SCREEN",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  FIND_PLACE_SCREEN = "FIND_PLACE_SCREEN",
  SHARE_PLACE_SCREEN = "SHARE_PLACE_SCREEN",
  PLACE_DETAIL_SCREEN = "PLACE_DETAIL_SCREEN"
}
